### ISSUE TITLE
[feature request] save name

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#100]
while I'm filing away issues, would be cool to be able to grab the current save name

I realize it's available in the vanilla http api, but I'd like to keep parity with non-dedicated server setups as well

**Comment by porisius** [comment]
Heh, possible from AFGGameState

	UFUNCTION( BlueprintPure, Category = "FactoryGame|Session" )
	FORCEINLINE FString GetSessionName() const { return mReplicatedSessionName; }
