### ISSUE TITLE
Train stations appear on 0,0,0

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#128]
Not sure if CSS bug or FRM bug, but all train stations currently appear at 0,0,0...

This may be my own save, noticed using a save pre-1.0.

**Comment by porisius** [comment]
They seem find to me...

  {
    "Name": "Serial0Back2Plat",
    "ClassName": "Build_TrainStation_C",
    "location": {
      "x": -62900,
      "y": 233200,
      "z": 21100.013671875,
      "rotation": 90
    },
    "TransferRate": 0,
    "InflowRate": 0,
    "OutflowRate": 0,
    "CargoInventory": [
      {
        "Name": "Freight Platform",
        "ClassName": "Build_TrainDockingStation_C",
        "location": {
          "x": -62900,
          "y": 234800,
          "z": 21100.013671875,
          "rotation": 180
        },
        "PowerInfo": {
          "CircuitGroupID": 1,
          "CircuitID": 4,
          "PowerConsumed": 0.100000001490116,
          "MaxPowerConsumed": 50
        },
        "TransferRate": 0,
        "InflowRate": 0,
        "OutflowRate": 0,
        "LoadingMode": "Loading",
        "LoadingStatus": "Idle",
        "DockingStatus": "None",
        "Inventory": []
      },
      {
        "Name": "Freight Platform",
        "ClassName": "Build_TrainDockingStation_C",
        "location": {
          "x": -62900,
          "y": 236400,
          "z": 21100.013671875,
          "rotation": 180
        },
        "PowerInfo": {
          "CircuitGroupID": 1,
          "CircuitID": 4,
          "PowerConsumed": 0.100000001490116,
          "MaxPowerConsumed": 50
        },
        "TransferRate": 0,
        "InflowRate": 0,
        "OutflowRate": 0,
        "LoadingMode": "Loading",
        "LoadingStatus": "Idle",
        "DockingStatus": "None",
        "Inventory": []
      }
    ],

**Comment by featheredtoast** [comment]
argh my save then, and this is a CSS bug in pre-1.0 save files...
