### ISSUE TITLE
Client Side doesn't work on dedicated servers

### ISSUE THREAD

**Issue by Cappecasper03** [porisius/FicsitRemoteMonitoring#161]
I have noticed that the mod doesn't work unless the server also has the mod in a dedicated server and if the server has it, the players also need it.

But I did see in the code that the "FicsitRemoteMonitoring_BP" is spawned on the server and replicated and if I change it to spawn on the client it does work so maybe it could be changed based on if the mod is installed on the client or a server?

**Comment by Fezalion** [comment]
FRM can be only on dedicated server, you as a player would only need SML to connect to a now modded server.

If the dedicated server doesn't have FRM, you having FRM as a client won't do anything, as mod needs to be in the "host" player, in this case the dedicated server.

**Comment by Cappecasper03** [comment]
I didn't check much but I do know the map and the player location did work but I guess you could be right and most of the other stuff doesn't work but I can check it more thoroughly later today.
