### ISSUE TITLE
FactoryCacheSeperate vs FactoryCacheGroup

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#21]
FactoryCacheSeparate is referenced both in the docs an in the Config_Factory.

FactoryCacheGroup is referenced in FRM_Factory Get Factory in where I'm assuming FactoryCacheSeparate should be.

![image](https://user-images.githubusercontent.com/1322534/209459088-359d7f51-83ff-4651-bc9a-1c8e707ec711.png)

**Comment by porisius** [comment]
![image](https://user-images.githubusercontent.com/47161774/209585960-69655307-5169-48d4-af82-df78b4367bc4.png)
Fixed, to be released in 0.8.13

**Comment by featheredtoast** [comment]
TYVM!
