### ISSUE TITLE
Stuttering observed with WebSocket_Delay when WebSocket_Autostart is false

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#22]
Steps to reproduce: Large-ish late game world. Websocket config disabled.

Set "FactoryCacheDelay": 600 (maximum) to ensure GetFactory is not at fault.
Observed stuttering/freezing for a second or two every 30 seconds.
Updated WebSocket_Delay to 60 (from default of 30). Observed the stuttering/freezing every 60 seconds.

I suspect this is caused by the subsystem's call to `getAllFunc`:
![image](https://user-images.githubusercontent.com/1322534/209460314-432aacb1-1d54-49bb-8c8b-bfcabe9e44c0.png)

Which in turn calls things like `getBelts` and `getPipes` which a large factory may have a LOT of.

This tick should probably also honor `WebSocket_Autostart` so as to avoid unnecessary computation.

**Comment by porisius** [comment]
Autostart is meant to be a setting to automatically start Serial/HTTP/Websocket on game load. Thus, no, I will not have it honor it.

I will, though, have it only run getAll only while the server is ACTUALLY running.

![image](https://user-images.githubusercontent.com/47161774/209586263-8f8672b7-ae79-4283-a64a-d58b07ea4914.png)

**Comment by featheredtoast** [comment]
Right, that makes sense. Thanks for addressing this - performance for non-websocket setups should be vastly improved 👍
