### ISSUE TITLE
Inventory not counting correctly

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#24]
I have multiple containers of batteries, but it's telling me I only have 2 from the getWorldInv route. Not sure what's causing it, but my guess its it's resetting rather than aggregating as there does exist a container with a stack of 2 batteries in my save.

Apologies for the short note this time, I don't have much to go off of this time

**Comment by porisius** [comment]
What does getStorageInv return? It ought to return the same (as they both run the same BP Function).

Also, are they vanilla containers or modded? There was a conversation I was having yesterday with someone about SF and mods, and I don't know for sure that modded containers work.

**Comment by featheredtoast** [comment]
This is all vanilla - the only mods I have installed are FRM and PAK Utility - I'll do some further investigations on this soon.

**Comment by featheredtoast** [comment]
From what I can tell, the issue is in how (map's) ADD works vs how the code is expecting them to work:

Looping (what's effectively) the following:
LocalBuffer.ADD('Battery', 200)
LocalBuffer.ADD('Battery', 200)
LocalBuffer.ADD('Battery', 200)

will *replace* the key 'Battery' with the value 200, rather than sum the values together.

I suspect it'd work better for both maps to pass through a FIND, and if not found then they can directly ADD, otherwise, SUM the new values....

Something like this might help (I'm a Unreal noob so this is completely untested, but it should help you get the idea):

![image](https://user-images.githubusercontent.com/1322534/210009415-d8bebfaa-12c3-44c2-aace-a9585c35cb5d.png)

**Comment by porisius** [comment]
![image](https://user-images.githubusercontent.com/47161774/210022908-636a5e0b-e0a2-42ea-8bc4-d93e69e90d8f.png)
close enough...
