### ISSUE TITLE
Add getGenerator route

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#37]
As requested, a reminder in the shape of a GitHub ticket!

Would you consider adding a route named something like `/getGenerators`? This would be a route that returns something similar to getFactory, but for power structures:

- building/generator type
- item consumption stats/min
- location
- power produced
- max power produced
- circuitID

**Comment by porisius** [comment]
Was thinking of this on the ride into work...

getGenerators - Similar to getFactory, but getFactory is a collection of all the factory buildings on the world. There are sub sets like, getAssembler, getConstructor, etc...

Ought I do something similar like getBioBurner, getCoalGen, getFuelGen, getNuclearGen. There was an experiment once with trying to get RefinedPower information, but MrHid and I talked about it and something about needing an 'interface'. Being a SysAdmin and an electronics technician makes me think like RS232, USB, PS2, etc, and I never followed up on understanding what he meant.

Anyways, trying to get SMR hammered out on the dedi changes, so while I will try, RL is chaotic and we need to hammer (test) out the SMR for when dedi becomes a thing.
