### ISSUE TITLE
Wrong JSON File output for /getDrone endpoint

### ISSUE THREAD

**Issue by Jonathan-Hofmann** [porisius/FicsitRemoteMonitoring#38]
As me and a friend of mine are currently trying to develop a dasboard with this endpoint we found out that the receiuved data cannot be parsed into a Web-JSON Object as it has a small error.

As one can see in the following screenshot the `FlyingSpeed` Key has the value 1,000 which gets parsed as the value 1 and then it gets confused by the `000`.
![grafik](https://user-images.githubusercontent.com/63954504/219027473-e257d3bd-51ed-413c-b0a9-accecfeb10c4.png)

I think the easiest fix would be to change the `FlyingSpeed` from f.ex. `1,000` to `1.000`. Then all should work fine again.

Thanks again for this great mod and I hope you also like our dashboard :D

**Comment by porisius** [comment]
Well, I think I found the problem. I think it might be better just to change it from an integer to a float. (mind the spaghetti)
![image](https://user-images.githubusercontent.com/47161774/219053059-e371d79e-9546-46e8-8b60-3abb87579620.png)

**Comment by Jonathan-Hofmann** [comment]
Perfect thanks!

**Comment by Jonathan-Hofmann** [comment]
Is the FlyingSpeed working in Version 0.8.25? As I still get the same `1,000,` value...

**Comment by porisius** [comment]
I just saw it, not sure why it didn't register as a static value for some reason. Probably because I looked at it before the caffeine kicked in.

**Comment by porisius** [comment]
I wonder if it is something that CSS hasn't finished, started on and stopped, or a bug. There are three flying modes, None/Docked, Flying, Traveling which are all ENums. These each have their own values (0, 1000, and 7000). Still checking, but I don't think the fault is mine now.

"FlyingSpeed":0,
"CurrentFlyingMode":"DFM_None"

"FlyingSpeed":1000,
"CurrentFlyingMode":"DFM_Flying"

"FlyingSpeed":7000,
"CurrentFlyingMode":"DFM_Travel"

**Comment by Jonathan-Hofmann** [comment]
So you `flyingSpeed` is not like the ´ForwardSpeed´ field from f.ex. the train-json? It is more like a targeted Speed?

If so maybe it would be better leaving `FlyingSpeed` out of the response JSON as we cannot use the JSON with the formatting error...

**Comment by porisius** [comment]
Curious why you are still getting that... this is my 0.8.25 test
![image](https://user-images.githubusercontent.com/47161774/219126543-a746a9d3-3d18-42cf-b17c-a520f24e830e.png)

**Comment by porisius** [comment]
0.8.26:
![image](https://user-images.githubusercontent.com/47161774/219127272-2433003e-1318-4569-9443-3cfaa012d688.png)
![image](https://user-images.githubusercontent.com/47161774/219128453-6850a2fe-6d2f-43da-829c-8bd6a9d38fb0.png)
I don't think you'll have that problem anymore... plus I am using the FGDrone actor's vector length to calculate a speed in knots, since that is what aircraft use anyways.

**Comment by Jonathan-Hofmann** [comment]
Nice! Works now like a charm!

**Comment by Jonathan-Hofmann** [comment]
Thank you again ;)
