### ISSUE TITLE
getWorldInv comma in JSON String Issue

### ISSUE THREAD

**Issue by arfla** [porisius/FicsitRemoteMonitoring#40]
Hi there, I am currently working on the dashboard project with @Jonathan-Hofmann. 

We have just noticed when trying to pull the getWorldInv Data that there is an issue with a comma in the count, so instead of 1000 it will output 1,000 breaking the JSON file. It would be greatly appreciated if this could be fixed, I have attached a screenshot. 

![image](https://user-images.githubusercontent.com/46490532/219720105-fb655a78-76f2-4d63-803b-b24a8280547b.png)

Thanks in advance, 
arfla

**Comment by arfla** [comment]
That is indeed strange how they passed the getAll verification... best of luck and thanks for taking the time.

**Comment by porisius** [comment]
This is what I use for testing...
https://jsonformatter.curiousconcept.com/#
Maybe the Fix JSON was checked, and it didn't report it?

**Comment by arfla** [comment]
I just used the same website and dumped in the /getAll this is what it comes back with:

![image](https://user-images.githubusercontent.com/46490532/219779492-df6982cb-4d08-4c1d-8f50-86bf325e1ffd.png)

Maybe when you do the testing, you don't have all the different vehicles and every item in the world and that's maybe why it does not throw an error perhaps?

**Comment by porisius** [comment]
I am wondering about localization, but you are on an English variant. The game does change the name of items for different languages based on what CSS sets. Just to verify, I know your buddy is German, what language are you playing on? I am on English (US), go figure, I'm an American.

![image](https://user-images.githubusercontent.com/47161774/219782739-b15bc027-b6d6-403f-b9bc-638ab5bfc4f7.png)

**Comment by arfla** [comment]
Well, it turns out that's what it is! Well done! I am playing on the language setting English UK and for some odd reason, it adds a comma. I just swapped over to English US and it worked fine, no commas.

**Comment by porisius** [comment]
I'll add that to the list of languages to test next time for localization issues. French and Italian are already on it.

**Comment by porisius** [comment]
Found more that were affected... hopefully this fixes all of them

**Comment by arfla** [comment]
Hey, thanks for the update. I just had a look, this is what /getWorldInv and /getStorageInv return for me:

![image](https://user-images.githubusercontent.com/46490532/219853250-4b56cd71-fef8-460c-9899-a4918e97b0e1.png)
![image](https://user-images.githubusercontent.com/46490532/219853280-24ff8f17-c5ef-4a0d-9e5e-b81087dbcde8.png)

It does this regardless if I am on English UK or US, did these work for you?

**Comment by porisius** [comment]
I think I forgot to change it back to the GAAoC after attempts to use the FGCentralStorageSubsystem failed.

**Comment by porisius** [comment]
0.8.29 is sent to the hopper

**Comment by arfla** [comment]
Amazing, that has fixed the issue, it is showing again and even on English UK there is no comma in the number. Thanks!
