### ISSUE TITLE
Duplicate Circuit IDs bloating getPower

### ISSUE THREAD

**Issue by porisius** [porisius/FicsitRemoteMonitoring#42]
Circuit IDs bloating getPower. The circuit information is coming from Satisfactory, and not the mod. Attempts to use Circuit Groups have failed, but I am engaging with others in the modding community for assistance.

**Comment by GalaxyVOID** [comment]
Why not just remove/ignore the duplicate circuit. Or if they are not the same but have the same ID just do like: Circuit 1 (1 or 2)

**Comment by porisius** [comment]
The circuit ID isn't something that I generate, it is acquired from the game. That's what makes it difficult.

![image](https://user-images.githubusercontent.com/47161774/222027726-30b6e00a-b972-4ac6-813b-c81303582a44.png)
![image](https://user-images.githubusercontent.com/47161774/222027854-ca2cb824-7f15-4ee4-8a75-bb003de605cb.png)

**Comment by GalaxyVOID** [comment]
Couldn't u make it so it ads _index example: Circuit ID 42_1, 42_2, 47_1

**Comment by porisius** [comment]
Fixed with SF 1.0 release
