### ISSUE TITLE
Porsius' Discord account got hacked.

### ISSUE THREAD

**Issue by SpaceGameDev568** [porisius/FicsitRemoteMonitoring#62]
@porisius Hey, your Discord account got hacked and just tried to dm me and get me to download malware. I didn't know if you were aware and couldn't find another way to contact you, so I'm sorry if this isn't the most appropriate method to get your attention.

**Comment by porisius** [comment]
Been hacked since August 8th, 2023. Ticket opened with Discord.
https://support.discord.com/hc/en-us/requests/38503552?page=1
