### ISSUE TITLE
0.10.0 - Default website/port loads on 8090

### ISSUE THREAD

**Issue by WizardShep** [porisius/FicsitRemoteMonitoring#63]
I've had to do a new install of Satisfactory Experimental and FRM version 0.10.0 and am experiencing the webserver auto-starting on port 8090 causing the website information not to display in the webpage.  Tried writing a new WebServer.cfg as this does not exist on new install and it does not respect starting up on 8080.  Looked at the code and see that the asset/js references port 8080 specifically.  

Auto-starting on this new port also is causing companion apps others have written to pull data into things like Grafana to fail.

**Comment by porisius** [comment]
There is something in the works... with the recent catastrophe plus being involved in making dedicated server mods a reality. There is also the pending engine update to UE 5.2. I hadn't touched base with @GalaxyVOID to follow up on the changes.

**Comment by GalaxyVOID** [comment]
?

**Comment by porisius** [comment]
@WizardShep, right now, I am trying to figure out what is going wrong about that setting now showing up in my test build.

However, you ought to be able to use the GitHub Pages variant of the UI. You will still need to have the mod's web service active, but you ought to be able to use this for it.

https://galaxyvoid.github.io/FRM-s-WebUI-Source/

**Comment by GalaxyVOID** [comment]
I just wanna say that the map doesn't work on the github version, everything else should be there

**Comment by GalaxyVOID** [comment]
> I've had to do a new install of Satisfactory Experimental and FRM version 0.10.0 and am experiencing the webserver auto-starting on port 8090 causing the website information not to display in the webpage. Tried writing a new WebServer.cfg as this does not exist on new install and it does not respect starting up on 8080. Looked at the code and see that the asset/js references port 8080 specifically.
> 
> Auto-starting on this new port also is causing companion apps others have written to pull data into things like Grafana to fail.

The UI now has an option to use anything URI that the UI thinks its from the mod, it also verifies it.

**Comment by porisius** [comment]
This should be resolved in 0.10.1. Sorry for the delay, but I was not ready to release a new version with the Engine update coming like it did.

Please confirm when you have a chance.

**Comment by porisius** [comment]
Issue ought to be resolved. Please let us know if it is know.
