### ISSUE TITLE
/getStorageInv only show first slot 

### ISSUE THREAD

**Issue by nutcracker89** [porisius/FicsitRemoteMonitoring#68]
Hello

when getting /getStorageInv container or any storage only shows one inventory slot and it is random

here is an json example

```json
{
  "properties": {
    "name": "Personal Storage Box",
    "type": "Storage Container"
  },
  "geometry": {
    "coordinates": {
      "X": 247995.234375,
      "Y": -153958.953125,
      "Z": 3835.646484375
    },
    "type": "Point"
  }
},
{
  "Name": "Storage Container",
  "ClassName": "Build_StorageContainerMk1_C",
  "location": {
    "x": 249185.234375,
    "y": -150100.265625,
    "z": 4062.712158203125,
    "rotation": 270
  },
  "inventory": [
    { "Name": "Iron Ingot", "ClassName": "Desc_IronIngot_C", "Amount": 100 }
  ],
  "features": {
    "properties": {
      "name": "Storage Container",
      "type": "Storage Container"
    },
    "geometry": {
      "coordinates": {
        "X": 249185.234375,
        "Y": -150100.265625,
        "Z": 4062.712158203125
      },
      "type": "Point"
    }
  }
}

**Comment by GalaxyVOID** [comment]
@nutcracker89 put the json exapmle into a code block with the json syntax

**Comment by porisius** [comment]
The item that is reported is dependent on what UE reports back first... it is not sorted.

Now as to why only one entry, I can look at it. Got any images of the inventories of those storage containers just for reference? Also, the mod is in the middle of a C++ rewrite, so the way to fix it might be to re-write it. XD

**Comment by nutcracker89** [comment]
@GalaxyVOID fixed
@porisius 
yes can post them

Personal Storage Box (HUB)
![bild](https://github.com/porisius/FicsitRemoteMonitoring/assets/65375221/6b1b7367-aea3-4338-887c-57f3174a4bec)

Storage Container
![bild](https://github.com/porisius/FicsitRemoteMonitoring/assets/65375221/d7ed7181-23f6-46da-84ce-88132faadd53)

Great work thou, i like this mod keep up the good work

**Comment by porisius** [comment]
That makes a LOT more sense now... at least for the storage container, I can see it being one "item" but it should be way higher than 100... LOL

Thanks, tonight is DnD night, so I will tackle this as soon as I am able.

**Comment by nutcracker89** [comment]
yeah no hurries  just when you have time :)

**Comment by porisius** [comment]
Solved in https://github.com/porisius/FicsitRemoteMonitoring/commit/4a1d443861ed6a6cd5c1b20b5a91208ee9192245
