### ISSUE TITLE
wrong API url

### ISSUE THREAD

**Issue by Minecrafter8001** [porisius/FicsitRemoteMonitoring#77]
the webserver is attempting to get data from http://localhost:8080/127.0.0.1:8080/ which isn't a valid URL
![image](https://github.com/user-attachments/assets/4c44feaf-29f9-4638-8902-704500c3f80b)

**Comment by nward** [comment]
Are you using a reverse proxy or similar? I had to rewrite the paths to make this work. Here's what I put in my nginx config, this removes the `/127.0.0.1:8080` bit from the URLs:
```
rewrite ^/127\.0\.0\.1:8080(.*)$ $1 break;
```

@porisius it would be great if the URLs that the HTML/js/etc. used were relative, rather than absolute with hostnames+ports - which would allow us to proxy it, and also put it at different paths.

**Comment by porisius** [comment]
That's more @V0IDL355's area than mine, but I will relay.

**Comment by V0IDL355** [comment]
Make sure u changed the api url in the settings tab

**Comment by nward** [comment]
Got it - thanks. I had seen you responding to other issues :-)

I may be able to submit a PR - I'm not at all familiar with this code base but know enough to be dangerous. I have a few other web things I'd like to fix as well (such as not sending both Transfer-Encoding and Content-Length in responses).

**Comment by nward** [comment]
> Make sure u changed the api url in the settings tab

Yes - I appreciate that this option exists. Using relative paths would mean we can access the app in multiple ways concurrently, without configuration changes.

**Comment by V0IDL355** [comment]
> Are you using a reverse proxy or similar? I had to rewrite the paths to make this work. Here's what I put in my nginx config, this removes the `/127.0.0.1:8080` bit from the URLs:
> ```
> rewrite ^/127\.0\.0\.1:8080(.*)$ $1 break;
> ```
> 
> @porisius it would be great if the URLs that the HTML/js/etc. used were relative, rather than absolute with hostnames+ports - which would allow us to proxy it, and also put it at different paths.

Donno what you mean by obsolete but u can put any thing that has http or https for the url as far as I know. Along as it matches the api scheme.

**Comment by nward** [comment]
"absolute" not "obsolete".

Relative paths means that the HTML/JS content returned by the server has links as simply `getPower`, rather than `127.0.0.1:8080/getPower` or `/getPower`. This way, the browser will add the hostname, port, and path prefix of the referring page, so that the content can be accessed through proxies etc. without any configuration required in the server.

**Comment by V0IDL355** [comment]
> "absolute" not "obsolete".

Was on mobile at that time and was tired xD

> Relative paths means that the HTML/JS content returned by the server has links as simply `getPower`, rather than `127.0.0.1:8080/getPower` or `/getPower`. This way, the browser will add the hostname, port, and path prefix of the referring page, so that the content can be accessed through proxies etc. without any configuration required in the server.

If you are talking about the web ui I won't prob add that thing since some people like to change the url of the api and making it to relative paths will most likely kill it

**Comment by V0IDL355** [comment]
> the webserver is attempting to get data from http://localhost:8080/127.0.0.1:8080/ which isn't a valid URL ![image](https://private-user-images.githubusercontent.com/133237713/375914864-4c44feaf-29f9-4638-8902-704500c3f80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTYzMTgsIm5iZiI6MTcyODg5NjAxOCwicGF0aCI6Ii8xMzMyMzc3MTMvMzc1OTE0ODY0LTRjNDRmZWFmLTI5ZjktNDYzOC04OTAyLTcwNDUwMGMzZjgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODUzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzg2MTVhZGNiODFhMmM2NGE0ODcyYzkyZTliNDU1ZTkxYzlkNjU1NTk4OTVmMGNmYjI0ZWU3NWY2NTFlMjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TIugo1xyQRrX8uhAkQQCiykEjnEJMcHTgvYZzBbIVE)

Found why: https://github.com/V0IDL355/FRM-s-WebUI-Source/blob/8a78f5fc52f9a324bf75bb6ce39a8b3e68909eb2/src/App.tsx#L14

**Comment by Minecrafter8001** [comment]
> Are you using a reverse proxy or similar? 

No this is totally stock
Fresh install

**Comment by V0IDL355** [comment]
> > Are you using a reverse proxy or similar?
> 
> No this is totally stock Fresh install

Idk if I fixed it in the newer UI but for now clear browser cookies or reset the API URL and it should work.

**Comment by V0IDL355** [comment]
> the webserver is attempting to get data from http://localhost:8080/127.0.0.1:8080/ which isn't a valid URL ![image](https://private-user-images.githubusercontent.com/133237713/375914864-4c44feaf-29f9-4638-8902-704500c3f80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTc1MTIsIm5iZiI6MTcyOTQ5NzIxMiwicGF0aCI6Ii8xMzMyMzc3MTMvMzc1OTE0ODY0LTRjNDRmZWFmLTI5ZjktNDYzOC04OTAyLTcwNDUwMGMzZjgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNzUzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzVhMDQyNjBiZGU1OGJmZDc3YTUwMThhYzQ0ODg0ZTMwMWNlODI1YmM1OWRhNzk5N2JiMTQwM2NjMDlmYjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YpxGzvV7l2hWm2FdGQI5ZFYfLbuG0erk1yn36H1XIiY)

Should be fixed when the new ui comes out to the main mod. 😄

**Comment by V0IDL355** [comment]
Should be fixed with the new ui.
