### ISSUE TITLE
[Question] Migrate HTTP endpoints to the official API?

### ISSUE THREAD

**Issue by EpocDotFr** [porisius/FicsitRemoteMonitoring#78]
Hi!

Not an issue, don't worry 😀

CSS said in a past announcement the official HTTPS API may be extended by mods. Do you plan to migrate FRM HTTP endpoints to the official API?

Thanks in advance and thank you for your awesome mod.

**Comment by porisius** [comment]
Pardon me as I am just waking up. Please hear me out.

Migrate, no, but there are plans to still use it in conjunction. My attempts to use the same technique that CSS is using doesn't allow for static file which is one of the features of FRM. Also, I need the engine for websockets.

I hope that answers your question.

**Comment by EpocDotFr** [comment]
Absolutely, thank you for clarifying that topic.

Cheers!

**Comment by porisius** [comment]
Sorry to necro a closed GHI, but I wanted to let you know there is progress.
![image](https://github.com/user-attachments/assets/8441a2d0-fd6f-4244-bf92-19bc154902b3)
