### ISSUE TITLE
Error with JSON when the game is set to French

### ISSUE THREAD

**Issue by Toshiball** [porisius/FicsitRemoteMonitoring#8]
Hello, sorry for my terrible English.
So I have the following error (screen below) when my game is in French and everything works when I am in English. So I want to report it for future people for whom its not working.

![image](https://user-images.githubusercontent.com/64008713/147277485-376bb4fb-6bfd-438c-aa4a-b068abd7a96f.png)

![image](https://user-images.githubusercontent.com/64008713/147277157-aa9dbf1d-d328-4d2f-87c1-42d83752594f.png)

**Comment by porisius** [comment]
Heh, I thought I swashed that bug a long time ago...

I see you in getPower. Let me check the function that is supposed to be handling that.

**Comment by porisius** [comment]
[FicsitRemoteMonitoring.zip](https://github.com/porisius/FicsitRemoteMonitoring/files/7771161/FicsitRemoteMonitoring.zip)
As much as I would like to just upload and close ticket, would you please verify that things show as they should on your side as well? Just extract the contents to the FicsitRemoteMonitoring folder and go ahead and fire up Satisfactory.

**Comment by Toshiball** [comment]
Now is this
![image](https://user-images.githubusercontent.com/64008713/147288281-3bd6d5f7-a40b-49fc-b1f9-f9271efd7484.png)

**Comment by porisius** [comment]
Okay, in my defense, I did fix the issue that was reported... 

Once I have the save you are having issues with regarding (https://github.com/porisius/FicsitRemoteMonitoring/issues/9) that I can test against, then I will send you over a dev build with both fixes so that we can solve them.

**Comment by porisius** [comment]
Okay, this contains the other fixes for power, as well as the vehicle crashes
[FicsitRemoteMonitoring.zip](https://github.com/porisius/FicsitRemoteMonitoring/files/7772794/FicsitRemoteMonitoring.zip)
.

I'm working out a localization issue with UE and GetActorLocation. This plays into https://github.com/porisius/FicsitRemoteMonitoring/issues/9
Localization: French
{
    "ID":"2",
    "PlayerName":"porisius",
    "location":{
        "x":-51â€¯787,305,
        "y":192â€¯328,891,
        "z":-1â€¯853,417,
        "rotation":191
    }
}
    
Localization: English
{
    "ID":"2",
    "PlayerName":"porisius",
    "location":{
        "x":-51787.304688,
        "y":192328.890625,
        "z":-1853.417358,
        "rotation":191
    }
}

**Comment by Toshiball** [comment]
The battery % is back 

![image](https://user-images.githubusercontent.com/64008713/147343263-758a1a82-2e6d-4034-89a7-9f449f4e5f1e.png)

in a file the gettrains is badly written

![image](https://user-images.githubusercontent.com/64008713/147343487-3dd8db35-74d2-4633-ad65-08cde1127f29.png)

**Comment by Toshiball** [comment]
I also just noticed that there are errors with the map

![image](https://user-images.githubusercontent.com/64008713/147343955-c44c4faf-4021-4cf1-8f91-c23362411bef.png)

**Comment by porisius** [comment]
Uploaded a new version of FRM 0.7.1 to SMR/SMM.

Bounds not valid is going to take research, but resolved the localization issues and URI crashes. However the other map elements are functional. Honestly, the included map was a concept, and I do have a few people that are willing to make a proper web. I am not a web developer.

If the Mod Manager doesn't update, it is probably because the versions match in the .uplugin. You can reinstall the mod without losing your configurations for Webhook, custom JSON paths, and delays.

**Comment by Toshiball** [comment]
Nice no error whit the game set on french ty you can close ! 😉

**Comment by Toshiball** [comment]
AH another error on Tractor 

![image](https://user-images.githubusercontent.com/64008713/147416797-e256a39c-b7b7-4e87-b081-458b36a6aae5.png)

**Comment by porisius** [comment]
Resolved.
![image](https://user-images.githubusercontent.com/47161774/147436254-77a14f85-9cd0-4ac1-8be8-75e9ef5c1f94.png)

All vehicles use the same function, so they all should work. Apparently the getVehicles were not connected in the getAll function which is used in the QA validation checks.
![image](https://user-images.githubusercontent.com/47161774/147436291-a84fc63c-7dfb-4d7e-886a-7f08fe9093c2.png)

**Comment by Toshiball** [comment]
Okay for is good

**Comment by Toshiball** [comment]
EDIT : In French Tractor have a issue again 

![image](https://user-images.githubusercontent.com/64008713/147594715-a9b70f9d-25d9-425e-b444-55325710bf2f.png)

**Comment by porisius** [comment]
Figures I forget those... I posted 0.7.3 and that should be done and done

**Comment by Toshiball** [comment]
Everything works for me
If you want I made a web page which groups together all the functions for the mod, here are some screens:

![image](https://user-images.githubusercontent.com/64008713/147666440-938ba453-a283-415e-9705-fc71a170c883.png)
![image](https://user-images.githubusercontent.com/64008713/147666450-2aac7c3e-15d4-456c-a471-881288976208.png)
![image](https://user-images.githubusercontent.com/64008713/147666474-326af760-31f1-444d-af27-3953687cae1f.png)
![image](https://user-images.githubusercontent.com/64008713/147666489-2fae733b-976c-4f24-b4f4-49019d953836.png)
![image](https://user-images.githubusercontent.com/64008713/147666503-2ffb06fe-8033-44dd-9808-16e1db7fcd7d.png)
![image](https://user-images.githubusercontent.com/64008713/147666511-5569ef05-957e-48db-a5e7-b07ac4bd7e68.png)
![image](https://user-images.githubusercontent.com/64008713/147666518-c3cdafc2-b757-4eb4-a265-50b52e8645a4.png)
![image](https://user-images.githubusercontent.com/64008713/147666550-e57c6e91-e7ee-4b38-830b-705d81b7255b.png)

**Comment by porisius** [comment]
Localization JSON issues solved. Just need to figure out the geo, may need to speak with Badger as he has been able to make some stuff happen.
