### ISSUE TITLE
PointsToCoupon Incorrectly Reflects Total Coupons in Sink Rather Than Points Needed for Next Coupon

### ISSUE THREAD

**Issue by shane04111** [porisius/FicsitRemoteMonitoring#84]
This means that instead of indicating how many points are needed to obtain the next coupon, the API is currently returning the total number of coupons already accumulated in the sink.

Steps to Reproduce:

Make a request to the getResourceSink or getExplorationSink API endpoint.
Examine the PointsToCoupon value in the response data.
Notice that it reflects the total number of coupons instead of the points required for the next coupon.

Request:

Please investigate and correct the PointsToCoupon field in the API response so that it accurately reflects the Points Until Next Coupon rather than the Number of Coupons in the Sink.

**Comment by porisius** [comment]
Potential fix: https://github.com/porisius/FicsitRemoteMonitoring/commit/0bbd7142b7be71883ac38ca8d7570a9fa17068d0
Commenting to bug track

Thanks for noting that.

**Comment by porisius** [comment]
Fixed in 1.1.0
