### ISSUE TITLE
Speed value reported by getBelts is not measured in items per minute

### ISSUE THREAD

**Issue by cosmopetrich** [porisius/FicsitRemoteMonitoring#85]
A call to `getBelts` will return a list of belts with `Speed` fields containing values which are double items per minute rate for a belt of that type. For example, a Mk.5 belt which can transport 780 items per minute will be listed in `getBelts` with `"Speed":1560`. See attached [getBelts.json](https://github.com/user-attachments/files/17392978/getBelts.json) for a sample with all belt types.

After looking into it a little, I don't think this is a bug as such. FRM calls `GetSpeed()` which in turn [just returns the belt's `mSpeed` property](https://github.com/satisfactorymodding/SatisfactoryModLoader/blob/04025f8209079ee869269fa3a64932fa3cde2b4b/Source/FactoryGame/Public/Buildables/FGBuildableConveyorBase.h#L156).

https://github.com/porisius/FicsitRemoteMonitoring/blob/47269f391d45337da3ee4b27c69e469c1e31ba71/Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp#L30

The issue is that the "doubled" values are what's actually present in the Unreal asset files. For example, a Mk.1 belt is shown below.

![mk1-ue](https://github.com/user-attachments/assets/19b4c19f-1d1d-484b-953e-41cfdfdcd76c)

My suspicion is that this value is used to determine the movement speed of items on the belt as visible in the game world. Satisfactory [uses `120` as a constant for how much space an item takes up on a belt](https://github.com/satisfactorymodding/SatisfactoryModLoader/blob/04025f8209079ee869269fa3a64932fa3cde2b4b/Source/FactoryGame/Public/Buildables/FGBuildableConveyorBase.h#L321), and that constant is used in calculations for whether there is space on a belt or not. Thus an `mSpeed` of 120 is effectively "items move one space along the belt every second", and thus the belt has a throughput of 60 items per minute. However, that's mostly speculation.

I suspect many users will see the Speed field and assume that it's the same "items per minute" unit that is reported in-game. I certainly did. I wonder if it would be worth doing one of the following.

- Add a note to the endpoint's documentation.
- Halve the value before returning it. I'm not sure that the "movement speed" is of much use outside the game itself, whereas the "items per minute" might be a useful way for detecting bottlenecks etc. Possibly it would be worth renaming it to "ItemsPerMinute" or something in case anyone familiar with the game's internals expects it to be the movement speed?
- Remove the field. That way it doesn't trick anyone, and clients can just keep a mapping of belt type to throughput if they need it.

**Comment by porisius** [comment]
@budak7273 confirms about speed being doubled.
Potential Fix: https://github.com/porisius/FicsitRemoteMonitoring/commit/1f55e8852efef679e31b092f25d41d80a2f92be3

**Comment by cosmopetrich** [comment]
I tested that fix while looking into something else in the 1.0.11 pre-release. The change LGTM. I'm seeing the correct items per minute for all 6 vanilla belt types.

**Comment by porisius** [comment]
Fixed in 1.1.0
