### ISSUE TITLE
ShipReturn weird formatting (getHubTerminal)

### ISSUE THREAD

**Issue by derpierre65** [porisius/FicsitRemoteMonitoring#88]
"ShipReturn" has a weird formatting in getHubTerminal, if the ship is docked/returned, e.g. "-121:-19:-22" (landed 121 hours and 19mins ago)

better would be "-121:19:22" or maybe a new property like ShipLanded/ShipReturned that contains "121:19:22" and ShipReturn would be an empty string or "00:00:00"

**Comment by porisius** [comment]
Resolved, but not released as new bugs were found, and was not able to support while on vacation.
https://github.com/porisius/FicsitRemoteMonitoring/commit/3f58debcb21dd1b8f6e045eec7484bc5b5c4b527

**Comment by porisius** [comment]
Fixed in 1.1.0
