### ISSUE TITLE
Inventory is now PlayerID (getDoggo)

### ISSUE THREAD

**Issue by derpierre65** [porisius/FicsitRemoteMonitoring#89]
the doggo inventory key is "Inventory" in the documentation, but it's currently PlayerID

**Comment by porisius** [comment]
Thanks, uploaded fix to test build location
https://github.com/porisius/FicsitRemoteMonitoring/commit/8e8a71e77ab16bace2f755eccd6b58449f9db635

**Comment by porisius** [comment]
Fixed in 1.1.0
