### ISSUE TITLE
Gets that don't work

### ISSUE THREAD

**Issue by Toshiball** [porisius/FicsitRemoteMonitoring#9]
Hello, yes me again xD
By testing some get do not work or they crash the game.
Here is the list

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/c4027/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/c4027/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

URI Handler | Result
-- | --
Get |  
Factory | Good
Assembler | Good
Blender | Good
Constructor | Good
Foundry | Good
Manufacturer | Good
Particle | Good
Refinery | Good
Smelter | Good
Drone | Good
DroneStation | Good
DropPod | Good
Explorer | **GameCrash**
Extractor | Good
ModList | Good
Power | Good
Player | Good
ProdStats | Good
ResourceNode | Good
ResoucreSink | Good
Schematics | Good
Switches | Good
Tractor | Good
Train | **404**
TrainStation | Good
Truck | **GameCrash**
TruckStation | Good
Vehicles | **GameCrash**
All | Good

</body>

</html>

**Comment by porisius** [comment]
Odd that tractor works but the other vehicles don't... they all use the same function, just different objects. Testing with the build for the OTHER issue you opened.

Train is a documentation error. Try getTrains.

As far as having two tickets, I see them as two separate issues, so two separate tickets.

Could you upload or DM me in Discord your save? I cannot replicate your error, both in English and French.

Sample from getVehicles (not full output)
{
      "ID":"1",
      "VehicleType":"Explorateur",
      "location":{
         "x":-70â€¯277,688,
         "y":225â€¯602,672,
         "z":-1â€¯816,857,
         "rotation":520.0
      },
      "ForwardSpeed":0,
      "CurrentGear":0,
      "EngineRPM":0,
      "Airborne":false,
      "AutoPilot":false,
      "FuelType":N/A,
      "FuelInventory":0,
      "ThrottlePercent":0,
      "PathName":"",
      "FollowingPath": false,
      "FuelUsed":"",
    "features": {
		"properties":
			{"type": "Explorateur"},
		"geometry": {
			"coordinates": {
				"x": -70â€¯277,688,
				"y": 225â€¯602,672,
				"z": -1â€¯816,857
			},
			"type": "Point"
		}
	}	
   }

**Comment by Toshiball** [comment]
For all my get tests I left my game in English so I was not tested for French.
The get trains works, but for the rest explore / truck / vehicles crash again.
it may be related to the mod I'm using so here is the list with my save:

https://www.mediafire.com/file/ph8hb4hjayri9w2/Save_Manu_U5_3.sav/file


[{
"SMRName": "BigStatues",
"ModName": "BigStatues",
"ModVersion": "2.0.2",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "DaisyChainPowerCables",
"ModName": "DaisyChainPowerCables",
"ModVersion": "2.0.2",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "BigStorageTank",
"ModName": "BigStorageTank",
"ModVersion": "2.0.3",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "FicsitRemoteMonitoring",
"ModName": "Ficsit Remote Monitoring",
"ModVersion": "0.7.1",
"AcceptAnyRemoteVersion": true
} ,{
"SMRName": "InventorySpace3",
"ModName": "InventorySpace3",
"ModVersion": "1.0.1",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "LinearMotion",
"ModName": "Linear Motion",
"ModVersion": "2.0.11",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "MarcioCommonLibs",
"ModName": "MarcioCommonLibs",
"ModVersion": "1.1.0",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "NoneEquipment",
"ModName": "NoneEquipment",
"ModVersion": "2.0.3",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "RegenAllHealth",
"ModName": "RegenAllHealth",
"ModVersion": "2.0.2",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "PowerChecker",
"ModName": "Power Checker",
"ModVersion": "2.1.3",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "SML",
"ModName": "Satisfactory Mod Loader",
"ModVersion": "3.3.0",
"AcceptAnyRemoteVersion": false
} ,{
"SMRName": "UtilityMod",
"ModName": "UtilityMod",
"ModVersion": "0.5.3",
"AcceptAnyRemoteVersion": false
}]

**Comment by porisius** [comment]
Able to replicate results... appears to be an issues with GetForwardSpeed. I'll see what I can glean and discover.

Version: 176027, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

FactoryGame_PhysXVehicles_Win64_Shipping!UWheeledVehicleMovementComponent::GetForwardSpeed() [D:\ws\SB-211116092526-440\UE4\Engine\Plugins\Runtime\PhysXVehicles\Source\PhysXVehicles\Private\WheeledVehicleMovementComponent.cpp:1398]
FactoryGame_PhysXVehicles_Win64_Shipping!UWheeledVehicleMovementComponent::execGetForwardSpeed() [D:\ws\SB-211116092526-440\UE4\Engine\Plugins\Runtime\PhysXVehicles\Intermediate\Build\Win64\FactoryGame\Inc\PhysXVehicles\WheeledVehicleMovementComponent.gen.cpp:540]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::CallFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:998]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2870]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLet() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2655]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2990]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2997]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1992]
FactoryGame_Engine_Win64_Shipping!AActor::ProcessEvent() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:917]
FactoryGame_BlueprintHttpServer_Win64_Shipping!FHttpServerRouteMulticastCallback_DelegateWrapper() [A:\workspace\SatisfactoryModLoader\Plugins\FicsitRemoteMonitoring\Source\BlueprintHttpServer\Private\BlueprintHttpNodes.h:12]
FactoryGame_BlueprintHttpServer_Win64_Shipping!<lambda_7268c591afce01ca4b149a6c8ab61369>::operator()() [A:\workspace\SatisfactoryModLoader\Plugins\FicsitRemoteMonitoring\Source\BlueprintHttpServer\Private\BlueprintHttpNodes.cpp:60]
FactoryGame_BlueprintHttpServer_Win64_Shipping!TBaseFunctorDelegateInstance<void __cdecl(FBlueprintHttpRequest const &,FBlueprintHttpResponse &),FDefaultDelegateUserPolicy,<lambda_7268c591afce01ca4b149a6c8ab61369> >::ExecuteIfSafe() [A:\Unreal Engine - CSS\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:838]
FactoryGame_Core_Win64_Shipping!TGraphTask<FAsyncGraphTask>::ExecuteTask() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:887]
FactoryGame_Core_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilIdle() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:611]
FactoryGame_Engine_Win64_Shipping!FFrameEndSync::Sync() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:10906]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5096]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Toshiball** [comment]
Okay Truck / explorer and Vehicles works well

**Comment by porisius** [comment]
Okay, this issue was about crashing. Since issue resolved, closing this issue.
