### ISSUE TITLE
add drone fuel stats

### ISSUE THREAD

**Issue by featheredtoast** [porisius/FicsitRemoteMonitoring#96]
good to have fuel type and fuel drain similar to vehicles

**Comment by V0IDL355** [comment]
Drone fuel like batteries?
https://github.com/porisius/FicsitRemoteMonitoring/blob/dev/Source%2FFicsitRemoteMonitoring%2FPrivate%2FFRM_Drones.cpp#L21

**Comment by cosmopetrich** [comment]
> Drone fuel like batteries? [`dev`/Source%2FFicsitRemoteMonitoring%2FPrivate%2FFRM_Drones.cpp#L21](https://github.com/porisius/FicsitRemoteMonitoring/blob/dev/Source%2FFicsitRemoteMonitoring%2FPrivate%2FFRM_Drones.cpp#L21)

Yeah, though as of 1.0 drones and drone ports also accept regular liquid/gas fuels (fuel/turbofuel/rocket/ionized) and uranium/plutonium cells in addition to batteries.

**Comment by porisius** [comment]
How much you want?

![image](https://github.com/user-attachments/assets/b2649a34-4cdb-40ea-867d-d4a89983fddf)

**Comment by featheredtoast** [comment]
all of those, probably would be good 🙏 

I am not sure what the difference is between EstimatedFuelCostRate and SingleTripFuelCost but the rest look helpful to surface.

**Comment by porisius** [comment]
![image](https://github.com/user-attachments/assets/dd4e46b8-8a78-4671-8da5-0fd8974d1af3)
![image](https://github.com/user-attachments/assets/79aec3e7-e6ad-41ff-919a-eb120d6aef90)

**Comment by featheredtoast** [comment]
![image](https://github.com/user-attachments/assets/3faf0e1d-7b13-4c80-a60d-6fc46209c815)
